### ISSUE TITLE
Samples seem out of date

### ISSUE THREAD

**Issue by Hawk5446** [gkmo/CarloSharp#9]
Version 1.0.7
The HelloWorld sample seems out of date or something.  I can build it and get it executing on windows fine but when I try to run the same app on Linux, I get errors stating it can not load Https://domain/index.html.  The window opens fine, just shows a 404 page and the console displays the contents of the error.

After digging around a bit in the source it looks like it defaults to Https://domain if the uri given does not start with http or https. 

I've messed around with it a bit and can not seem to get it to work right.  Here is the code from my initial attempt.

Code:
`            Options options = new Options();
            options.Title = "test";
            options.Width = 1024;
            options.Height = 600;
            options.Channel = new string[] { "stable" }; //new string[] { "canary" }; //new string[] { "*" };
            app = Carlo.Launch(options);
            app.ServeFolder("./wwwroot");
            app.Load("index.html");
            app.Exit += OnAppExit;
            var thread = new Thread((s) =>
            {
                while (!mustExit)
                {
                    app?.MainWindow?.SendIpcMessageAsync("message-from-csharp", DateTime.Now.ToString());
                    Thread.Sleep(1000);
                }
            });
            thread.Start();
            _exitEvent.WaitOne();
`

Error details:
hawk@hawk-VirtualBox:~/Desktop/test$ dotnet ConsoleApp1.dll
DEBUG:Configuring browser
DEBUG:Page created at data:text/html,
DEBUG:Load page index.html
DEBUG:Initializing network interception...
DEBUG:Navigating the page to index.html
DEBUG:intercepted: https://domain/index.html
DEBUG:next handler https://domain/index.html
DEBUG:request url: https://domain/index.html
DEBUG:prefix: /
DEBUG:pathname: index.html
DEBUG:deferToBrowser  https://domain/index.html
DEBUG:resolve  https://domain/index.html
Unhandled exception. System.AggregateException: One or more errors occurred. (net::ERR_NAME_RESOLUTION_FAILED at https://domain/index.html at https://domain/index.html)
 ---> PuppeteerSharp.NavigationException: net::ERR_NAME_RESOLUTION_FAILED at https://domain/index.html at https://domain/index.html
 ---> PuppeteerSharp.NavigationException: net::ERR_NAME_RESOLUTION_FAILED at https://domain/index.html
   at PuppeteerSharp.FrameManager.NavigateAsync(CDPSession client, String url, String referrer, String frameId)
   at PuppeteerSharp.FrameManager.NavigateFrameAsync(Frame frame, String url, NavigationOptions options)
   --- End of inner exception stack trace ---
   at PuppeteerSharp.FrameManager.NavigateFrameAsync(Frame frame, String url, NavigationOptions options)
   at CarloSharp.Window.LoadAsync(String uri, Options options)
   at CarloSharp.App.LoadAsync(String uri, Options options)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at CarloSharp.App.Load(String uri, Options options)
   at ConsoleApp1.CarloApp.StartApp(String title, Int32 width, Int32 height) in C:\Users\hawk\source\repos\ConsoleApp1\ConsoleApp1\CarloApp.cs:line 26
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\hawk\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 11
Aborted (core dumped)

**Comment by Hawk5446** [comment]
well.. seems my copy operation to the linux machine failed and didnt copy anything from the wwwroot folder... durrrr.....  After making sure the file were there it runs fine.
